import React from 'react';
import {
  ArrowLeft,
  Database,
  Eye,
  FileText,
  Link2,
  LockKeyhole,
  Mail,
  RefreshCw,
  ShieldCheck,
  UserRoundCheck,
} from 'lucide-react';
import { COMPANY_INFO } from '../data/companyData';

interface PrivacyPolicyPageProps {
  onNavigate: (page: string) => void;
}

type Section = {
  title: string;
  icon: React.ComponentType<{ className?: string; strokeWidth?: number }>;
  paragraphs?: string[];
  bullets?: string[];
};

const sections: Section[] = [
  {
    title: '1. Information We May Collect',
    icon: Database,
    paragraphs: [
      'When you contact Averon Freight Solutions LLP through this website, request a quotation, make a shipment-status enquiry, call us, or email us, we may receive information that you choose to provide.',
    ],
    bullets: [
      'Name, company name and business contact details.',
      'Email address, telephone number and WhatsApp number.',
      'Shipment origin, destination, transport mode and cargo-related information.',
      'Messages, enquiries, quotation requirements and other information you voluntarily submit.',
      'Basic technical information that may be generated by the website or approved analytics services, such as browser type, device type, pages visited and general usage information.',
    ],
  },
  {
    title: '2. How We Use Information',
    icon: Eye,
    paragraphs: [
      'Information received through the website may be used for legitimate business purposes connected with your enquiry or our services.',
    ],
    bullets: [
      'To respond to enquiries and quotation requests.',
      'To understand shipment requirements and coordinate the next operational step.',
      'To provide customer support and shipment-status assistance.',
      'To communicate about services, documentation or information requested by you.',
      'To maintain website security, reliability and service quality.',
      'To comply with applicable legal, regulatory or record-keeping requirements.',
    ],
  },
  {
    title: '3. Sharing of Information',
    icon: UserRoundCheck,
    paragraphs: [
      'Averon does not intend to sell personal information. Information may be shared only where reasonably necessary for the purpose for which it was provided, for business operations, or where disclosure is required by law.',
      'Depending on the shipment or enquiry, information may need to be shared with service providers, logistics partners, carriers, customs-related parties or other parties involved in coordinating the requested service. Any such sharing should be limited to information reasonably required for that purpose.',
    ],
  },
  {
    title: '4. Data Security and Retention',
    icon: LockKeyhole,
    paragraphs: [
      'We aim to use reasonable administrative and technical safeguards appropriate to the information handled through the website. However, no internet transmission or electronic storage method can be guaranteed to be completely secure.',
      'Information may be retained for as long as reasonably necessary to respond to an enquiry, support an ongoing business relationship, maintain appropriate records, resolve disputes, or meet applicable legal and regulatory obligations.',
    ],
  },
  {
    title: '5. Cookies, Analytics and Similar Technologies',
    icon: FileText,
    paragraphs: [
      'The website may use essential browser technologies required for normal operation. If analytics, advertising or other non-essential tracking tools are added in the future, the website should be updated to reflect the tools actually in use and any consent requirements that apply.',
      'Google Analytics or similar measurement tools should only be enabled after Averon approves the implementation and the related privacy disclosures are updated.',
    ],
  },
  {
    title: '6. Third-Party Websites and Services',
    icon: Link2,
    paragraphs: [
      'This website may link to third-party websites or services, including social networks, email applications, mapping services or logistics-related providers. Those third parties operate under their own privacy practices, and Averon is not responsible for the content or privacy practices of external websites.',
    ],
  },
  {
    title: '7. Your Choices and Requests',
    icon: ShieldCheck,
    paragraphs: [
      'You may contact Averon if you want to ask what contact information you previously provided through an enquiry, request a correction, or raise a privacy-related concern. Requests will be handled subject to applicable law, legitimate business requirements and record-retention obligations.',
    ],
  },
  {
    title: '8. Changes to This Privacy Policy',
    icon: RefreshCw,
    paragraphs: [
      'This Privacy Policy may be updated when the website, business processes, legal requirements or third-party services change. The revised version will be published on this page with an updated effective date.',
    ],
  },
];

export const PrivacyPolicyPage: React.FC<PrivacyPolicyPageProps> = ({ onNavigate }) => (
  <div className="bg-white text-[#14263d]">
    <section className="relative overflow-hidden bg-[#071a33] pb-14 pt-16 text-white sm:pb-16 sm:pt-20 lg:pb-20 lg:pt-24">
      <div className="absolute right-[-80px] top-[-100px] h-72 w-72 rounded-full border border-[#c9a227]/20" />
      <div className="absolute right-4 top-8 h-40 w-40 rounded-full border border-white/5" />

      <div className="relative mx-auto max-w-[1100px] px-4 sm:px-6 lg:px-8">
        <button
          type="button"
          onClick={() => onNavigate('home')}
          className="mb-8 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-slate-300 transition hover:text-[#d4af37]"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Home
        </button>

        <div className="text-[11px] font-extrabold uppercase tracking-[0.2em] text-[#d4af37]">
          Legal & Privacy
        </div>
        <h1 className="mt-4 text-4xl font-extrabold tracking-[-0.035em] sm:text-5xl">
          Privacy Policy
        </h1>
        <p className="mt-5 max-w-[760px] text-sm leading-7 text-slate-300 sm:text-base">
          This policy explains how Averon Freight Solutions LLP may collect, use and handle information received through this website and related business enquiries.
        </p>
        <p className="mt-4 text-xs font-semibold uppercase tracking-[0.12em] text-slate-400">
          Effective date: 10 October 2026
        </p>
      </div>
    </section>

    <section className="bg-[#f8f6f0] py-14 sm:py-16 lg:py-20">
      <div className="mx-auto grid max-w-[1100px] gap-8 px-4 sm:px-6 lg:grid-cols-[minmax(0,1fr)_280px] lg:px-8">
        <div className="space-y-5">
          <div className="border border-slate-200 bg-white p-6 shadow-[0_16px_45px_rgba(7,26,51,.05)] sm:p-8">
            <h2 className="text-xl font-extrabold text-[#071a33]">About this policy</h2>
            <p className="mt-3 text-sm leading-7 text-slate-700">
              This Privacy Policy applies to information received through the Averon Freight Solutions LLP website and website-related communications. It does not replace separate contractual, operational or regulatory obligations that may apply to a shipment, customer account, quotation or service engagement.
            </p>
          </div>

          {sections.map((section) => {
            const Icon = section.icon;
            return (
              <section
                key={section.title}
                className="border border-slate-200 bg-white p-6 shadow-[0_10px_30px_rgba(7,26,51,.035)] sm:p-8"
              >
                <div className="flex items-start gap-4">
                  <div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#071a33] text-[#d4af37]">
                    <Icon className="h-4.5 w-4.5" strokeWidth={1.8} />
                  </div>
                  <div className="min-w-0">
                    <h2 className="text-lg font-extrabold text-[#071a33] sm:text-xl">
                      {section.title}
                    </h2>
                    {section.paragraphs?.map((paragraph) => (
                      <p key={paragraph} className="mt-3 text-sm leading-7 text-slate-700">
                        {paragraph}
                      </p>
                    ))}
                    {section.bullets && (
                      <ul className="mt-4 space-y-2.5 text-sm leading-6 text-slate-700">
                        {section.bullets.map((item) => (
                          <li key={item} className="flex items-start gap-3">
                            <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#c9a227]" />
                            <span>{item}</span>
                          </li>
                        ))}
                      </ul>
                    )}
                  </div>
                </div>
              </section>
            );
          })}
        </div>

        <aside className="h-fit border border-slate-200 bg-[#071a33] p-6 text-white shadow-[0_18px_45px_rgba(7,26,51,.12)] lg:sticky lg:top-28">
          <div className="grid h-11 w-11 place-items-center rounded-full border border-[#c9a227] text-[#d4af37]">
            <ShieldCheck className="h-5 w-5" />
          </div>
          <h2 className="mt-5 text-lg font-extrabold">Privacy Questions</h2>
          <p className="mt-3 text-sm leading-6 text-slate-300">
            Contact Averon Freight Solutions LLP if you have a privacy-related question about information submitted through this website.
          </p>

          <div className="mt-6 border-t border-white/10 pt-5">
            <a
              href={`mailto:${COMPANY_INFO.emails[0]}`}
              className="inline-flex items-center gap-2 break-all text-sm font-bold text-white transition hover:text-[#d4af37]"
            >
              <Mail className="h-4 w-4 shrink-0 text-[#d4af37]" />
              {COMPANY_INFO.emails[0]}
            </a>
            <p className="mt-4 text-xs leading-5 text-slate-400">
              {COMPANY_INFO.address}
            </p>
          </div>
        </aside>
      </div>
    </section>
  </div>
);
